# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Syyu
tagline:          "Always Up-to-date"
description:      "Updates on my current projects"
url:              https://mreichardt95.github.io/
baseurl:          /syyu/

author:
  name:           'Milian Reichardt'
  url:            https://mreichardt95.github.io/syyu/

paginate:         1

# Custom vars
version:          1.0.0