# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            xvzf
tagline:          "prepend tar"
description:      "Extracted view of my projects - partly in english, partly german"
url:              https://github.com/xvzf
baseurl:          /

author:
  name:           'Matthias Riegler'
  url:            http://blog.xvzf.tech

paginate:         1

# Custom vars
version:          1.0.0